file(READ "${MANIFEST}" manifest)
file(READ "${MANIFEST}" manifest_hex HEX)

if(manifest_hex MATCHES "^efbbbf")
    message(FATAL_ERROR "ToolchainManifest must not contain a UTF-8 BOM")
endif()
if(manifest_hex MATCHES "0d")
    message(FATAL_ERROR "ToolchainManifest must use LF newlines")
endif()
if(NOT manifest_hex MATCHES "0a$")
    message(FATAL_ERROR "ToolchainManifest must end in one newline")
endif()
if(manifest_hex MATCHES "0a0a$")
    message(FATAL_ERROR "ToolchainManifest has more than one final newline")
endif()
if(manifest MATCHES "([A-Za-z]:[/\\\\]|timestamp|hostname|username|dirty|branch)")
    message(FATAL_ERROR "ToolchainManifest contains a forbidden path or volatile field")
endif()

function(assert_json expected)
    set(path ${ARGN})
    string(JSON actual ERROR_VARIABLE json_error GET "${manifest}" ${path})
    if(json_error)
        message(FATAL_ERROR "Invalid manifest JSON at ${path}: ${json_error}")
    endif()
    if(NOT actual STREQUAL "${expected}")
        message(FATAL_ERROR "Manifest mismatch at ${path}: '${actual}' != '${expected}'")
    endif()
endfunction()

assert_json("rgsml.toolchain_manifest" artifactId)
assert_json("1" schemaVersion)
assert_json("RGS MasterLab" productName)
assert_json("${EXPECTED_SYSTEM}" target systemName)
assert_json("${EXPECTED_ARCHITECTURE}" target architecture)
assert_json("${EXPECTED_SDK}" target windowsSdkVersion)
assert_json("${EXPECTED_CMAKE}" buildSystem cmakeVersion)
assert_json("${EXPECTED_GENERATOR}" buildSystem generator)
assert_json("${EXPECTED_PLATFORM}" buildSystem generatorPlatform)
assert_json("${EXPECTED_COMPILER_ID}" compiler id)
assert_json("${EXPECTED_COMPILER_VERSION}" compiler version)
assert_json("${EXPECTED_TOOLSET}" compiler toolset)
assert_json("${EXPECTED_QT}" qt version)
assert_json("6.8" qt minimumVersion)
assert_json("${EXPECTED_GIT}" sourceControl gitVersion)
assert_json("20" language cxxStandard)
assert_json("OFF" language extensions)
