#!/usr/bin/env python3
"""Generate the frozen playback-only 44.1/48 kHz SRC coefficient assets.

This tool is intentionally outside the ordinary CMake build. It requires
gmpy2/MPFR and never records the interpreter or environment path in an asset.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from dataclasses import dataclass
from pathlib import Path

import gmpy2


SCHEMA_ID = "rgsml.playback-src.kernel-manifest/1.0.0"
ALGORITHM_VERSION = "rgsml.playback-src.polyphase-fir/1.0.0"
KERNEL_POLICY_ID = "rgsml.playback-src.kernel.kaiser-sinc/1.0.0"
RATE_POLICY_ID = "rgsml.playback-src.rates.44100-48000/1.0.0"
BOUNDARY_POLICY_ID = "rgsml.src.boundary.even-reflect/1.0.0"
FRAME_MAP_POLICY_ID = "rgsml.src.frame-map.half-open-ceil/1.0.0"

F_MIN = 44_100
CUTOFF_HZ = 21_025
TAPS_PER_PHASE = 192
BETA_NUMERATOR = 613_263
BETA_DENOMINATOR = 50_000
INITIAL_PRECISION_BITS = 256
MAX_PRECISION_BITS = 2_048


@dataclass(frozen=True)
class KernelSpec:
    fin: int
    fout: int
    l: int
    m: int

    @property
    def count(self) -> int:
        return self.l * TAPS_PER_PHASE + 1

    @property
    def delay(self) -> int:
        return (self.count - 1) // 2

    @property
    def stem(self) -> str:
        return f"playback_src_kernel_{self.fin}_{self.fout}"


SPECS = (
    KernelSpec(44_100, 48_000, 160, 147),
    KernelSpec(48_000, 44_100, 147, 160),
)


def _context(precision: int) -> gmpy2.context:
    context = gmpy2.get_context().copy()
    context.precision = precision
    context.round = gmpy2.RoundToNearest
    return context


def _i0(value: gmpy2.mpfr, precision: int) -> gmpy2.mpfr:
    term = gmpy2.mpfr(1)
    total = gmpy2.mpfr(1)
    quarter_square = (value * value) / 4
    threshold = gmpy2.mpfr(2) ** (-(precision + 32))
    order = 1
    while True:
        term = term * quarter_square / (order * order)
        updated = total + term
        if abs(term) <= abs(updated) * threshold:
            return updated
        total = updated
        order += 1
        if order > 100_000:
            raise RuntimeError("I0 series did not converge")


def _generate_at_precision(spec: KernelSpec, precision: int) -> list[int]:
    with gmpy2.context(_context(precision)):
        pi = gmpy2.const_pi()
        beta = gmpy2.mpfr(BETA_NUMERATOR) / BETA_DENOMINATOR
        denominator = _i0(beta, precision)
        cutoff = gmpy2.mpfr(CUTOFF_HZ) / (spec.l * F_MIN)
        two_cutoff = 2 * cutoff
        delay = spec.delay
        raw_left: list[gmpy2.mpfr] = []

        for j in range(delay + 1):
            u = j - delay
            if u == 0:
                sinc = gmpy2.mpfr(1)
            else:
                z = two_cutoff * u
                sinc = gmpy2.sin(pi * z) / (pi * z)
            ratio = gmpy2.mpfr(u) / delay
            radicand = max(gmpy2.mpfr(0), 1 - ratio * ratio)
            window = _i0(beta * gmpy2.sqrt(radicand), precision) / denominator
            raw_left.append(two_cutoff * sinc * window)

        raw = raw_left + list(reversed(raw_left[:-1]))
        normalization_sum = gmpy2.mpfr(0)
        for value in raw:
            normalization_sum += value
        scale = gmpy2.mpfr(spec.l) / normalization_sum
        return [
            struct.unpack("<Q", struct.pack("<d", float(value * scale)))[0]
            for value in raw
        ]


def generate_with_ziv_stability(spec: KernelSpec) -> tuple[list[int], int]:
    precision = INITIAL_PRECISION_BITS
    previous = _generate_at_precision(spec, precision)
    while precision < MAX_PRECISION_BITS:
        precision *= 2
        current = _generate_at_precision(spec, precision)
        if current == previous:
            return current, precision
        previous = current
    raise RuntimeError(
        f"Ziv final-rounding stability was not reached for {spec.fin}->{spec.fout}"
    )


def coefficient_bytes(bits: list[int]) -> bytes:
    return b"".join(struct.pack("<Q", value) for value in bits)


def render_inc(spec: KernelSpec, bits: list[int]) -> bytes:
    lines = [
        "// Generated by tools/qualification/playback_src/generate.py; do not edit.\n",
        f"// {spec.fin} -> {spec.fout}; L={spec.l}; M={spec.m}; T={TAPS_PER_PHASE}; N={spec.count}\n",
    ]
    for offset in range(0, len(bits), 4):
        values = ", ".join(
            f"UINT64_C(0x{value:016x})" for value in bits[offset : offset + 4]
        )
        lines.append(f"    {values},\n")
    return "".join(lines).encode("ascii")


def _write_or_check(path: Path, data: bytes, check: bool) -> None:
    if check:
        if not path.is_file() or path.read_bytes() != data:
            raise RuntimeError(f"asset differs: {path.as_posix()}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_bytes(data)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[3],
        help="repository root (defaults to the root containing this tool)",
    )
    parser.add_argument("--check", action="store_true", help="verify checked-in bytes")
    args = parser.parse_args()
    root = args.repo_root.resolve()

    manifest_entries: list[dict[str, object]] = []
    for spec in SPECS:
        bits, proven_precision = generate_with_ziv_stability(spec)
        if bits != list(reversed(bits)):
            raise RuntimeError(f"symmetry failure for {spec.fin}->{spec.fout}")
        packed = coefficient_bytes(bits)
        digest = hashlib.sha256(packed).hexdigest()
        relative = Path("audio/src/internal") / f"{spec.stem}.inc"
        _write_or_check(root / relative, render_inc(spec, bits), args.check)
        manifest_entries.append(
            {
                "algorithmVersion": ALGORITHM_VERSION,
                "fin": spec.fin,
                "fout": spec.fout,
                "L": spec.l,
                "M": spec.m,
                "T": TAPS_PER_PHASE,
                "N": spec.count,
                "kernelSha256": digest,
                "coefficientAsset": relative.as_posix(),
                "zivStablePrecisionBits": proven_precision,
            }
        )
        print(
            f"{spec.fin}->{spec.fout} N={spec.count} "
            f"sha256={digest} ziv={proven_precision}"
        )

    manifest = {
        "schemaId": SCHEMA_ID,
        "capabilityId": "rgsml.audio.src.playback",
        "algorithmVersion": ALGORITHM_VERSION,
        "kernelPolicyId": KERNEL_POLICY_ID,
        "ratePolicyId": RATE_POLICY_ID,
        "boundaryPolicyId": BOUNDARY_POLICY_ID,
        "frameMapPolicyId": FRAME_MAP_POLICY_ID,
        "canonicalCoefficientEncoding": "ieee754-binary64-uint64-little-endian-j-ascending",
        "generator": {
            "transcendentalEvaluator": "MPFR",
            "initialPrecisionBits": INITIAL_PRECISION_BITS,
            "precisionSequence": "256,512,1024,...",
            "finalTarget": "IEEE binary64",
            "finalRounding": "round-to-nearest-ties-to-even",
            "termination": "Ziv final-rounding stability",
            "gmpy2Version": gmpy2.version(),
            "mpfrVersion": gmpy2.mpfr_version(),
        },
        "design": {
            "fminHz": F_MIN,
            "passbandEdgeHz": 20_000,
            "cutoffHz": CUTOFF_HZ,
            "stopbandEdgeHz": 22_050,
            "transitionHz": 2_050,
            "designAttenuationDb": 120,
            "beta": "613263/50000",
            "tapsPerPhase": TAPS_PER_PHASE,
        },
        "kernels": manifest_entries,
    }
    manifest_bytes = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    _write_or_check(
        root / "tests/audio_golden/playback_src/kernel_manifest.json",
        manifest_bytes,
        args.check,
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
