#include "windows_window_chrome_helper.hpp"

#ifdef _WIN32
#include <QCoreApplication>
#include <QPoint>
#include <QPointF>

#ifndef NOMINMAX
#define NOMINMAX
#endif

#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>
#include <windowsx.h>

namespace rgsml::app {

WindowsWindowChromeHelper::WindowsWindowChromeHelper(QQuickWindow* window)
    : window_(window)
{
    if (window_ != nullptr) {
        if (!window_->handle()) {
            window_->create();
        }
        nativeWindowId_ = static_cast<quintptr>(window_->winId());

        // Install event filter BEFORE style modifications / SetWindowPos(SWP_FRAMECHANGED)
        // so the very first WM_NCCALCSIZE generated by SWP_FRAMECHANGED is intercepted and strips the standard frame.
        QCoreApplication::instance()->installNativeEventFilter(this);

        const auto hwnd = reinterpret_cast<HWND>(nativeWindowId_);
        const LONG_PTR style = GetWindowLongPtrW(hwnd, GWL_STYLE);
        SetWindowLongPtrW(hwnd, GWL_STYLE, style | WS_THICKFRAME | WS_MAXIMIZEBOX | WS_CAPTION | WS_SYSMENU);
        SetWindowPos(
            hwnd,
            nullptr,
            0,
            0,
            0,
            0,
            SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED);
    }
}

WindowsWindowChromeHelper::~WindowsWindowChromeHelper()
{
    if (QCoreApplication::instance() != nullptr) {
        QCoreApplication::instance()->removeNativeEventFilter(this);
    }
}

void WindowsWindowChromeHelper::add_exclusion_item(QQuickItem* item)
{
    if (item != nullptr) {
        exclusions_.push_back(item);
    }
}

bool WindowsWindowChromeHelper::nativeEventFilter(
    const QByteArray& eventType,
    void* message,
    qintptr* result)
{
    Q_UNUSED(eventType);
    if (window_ == nullptr || nativeWindowId_ == 0 || message == nullptr || result == nullptr) {
        return false;
    }

    auto* msg = static_cast<MSG*>(message);
    if (msg->hwnd != reinterpret_cast<HWND>(nativeWindowId_)) {
        return false;
    }

    if (msg->message == WM_NCCALCSIZE) {
        if (msg->wParam == TRUE) {
            *result = 0;
            return true;
        }
    }


    return false;
}

}  // namespace rgsml::app
#endif
